data:extend({
	{
		type = "string-setting",
		name = "preset",
		setting_type = "startup",
		allowed_values = {"blood-red", "rainbow", "green", "purple", "puke", "custom"},
		default_value = "blood-red",
		order = "a",
		per_user = false,
	},
	{
		type = "double-setting",
		name = "r",
		setting_type = "startup",
		default_value = 0.3,
		maximum_value = 1,
		minimum_value = 0,
		order = "ab",
		per_user = false,
	},
		{
		type = "double-setting",
		name = "g",
		setting_type = "startup",
		default_value = 0,
		maximum_value = 1,
		minimum_value = 0,
		order = "b",
		per_user = false,
	},
		{
		type = "double-setting",
		name = "b",
		setting_type = "startup",
		default_value = 0.01,
		maximum_value = 1,
		minimum_value = 0,
		order = "c",
		per_user = false,
	},
	{
		type = "double-setting",
		name = "a",
		setting_type = "startup",
		default_value = 0.7,
		maximum_value = 1,
		minimum_value = 0,
		order = "d",
		per_user = false,
	},
	{
		type = "double-setting",
		name = "splatter-r",
		setting_type = "startup",
		default_value = 0.24,
		maximum_value = 1,
		minimum_value = 0,
		order = "da",
		per_user = false,
	},
		{
		type = "double-setting",
		name = "splatter-g",
		setting_type = "startup",
		default_value = 0,
		maximum_value = 1,
		minimum_value = 0,
		order = "db",
		per_user = false,
	},
		{
		type = "double-setting",
		name = "splatter-b",
		setting_type = "startup",
		default_value = 0.006,
		maximum_value = 1,
		minimum_value = 0,
		order = "dc",
		per_user = false,
	},
	{
		type = "double-setting",
		name = "splatter-a",
		setting_type = "startup",
		default_value = 0.7,
		maximum_value = 1,
		minimum_value = 0,
		order = "dd",
		per_user = false,
	},
		{
		type = "double-setting",
		name = "particle-r",
		setting_type = "startup",
		default_value = 0.3,
		maximum_value = 1,
		minimum_value = 0,
		order = "de",
		per_user = false,
	},
		{
		type = "double-setting",
		name = "particle-g",
		setting_type = "startup",
		default_value = 0,
		maximum_value = 1,
		minimum_value = 0,
		order = "df",
		per_user = false,
	},
		{
		type = "double-setting",
		name = "particle-b",
		setting_type = "startup",
		default_value = 0.01,
		maximum_value = 1,
		minimum_value = 0,
		order = "dg",
		per_user = false,
	},
	{
		type = "double-setting",
		name = "particle-a",
		setting_type = "startup",
		default_value = 0.7,
		maximum_value = 1,
		minimum_value = 0,
		order = "dh",
		per_user = false,
	},
		{
		type = "double-setting",
		name = "scale",
		setting_type = "startup",
		default_value = 1.05,
		maximum_value = 5,
		minimum_value = 0.01,
		order = "f",
		per_user = false,
	},
		{
		type = "double-setting",
		name = "splatterscale",
		setting_type = "startup",
		default_value = 1.3,
		maximum_value = 5,
		minimum_value = 0.01,
		order = "g",
		per_user = false,
	},
	{
		type = "double-setting",
		name = "particlescale",
		setting_type = "startup",
		default_value = 1,
		maximum_value = 5,
		minimum_value = 0.01,
		order = "h",
		per_user = false,
	},
	{
		type = "int-setting",
		name = "splatterduration",
		setting_type = "startup",
		default_value = 45,
		maximum_value = 9999999,
		minimum_value = 0,
		order = "i",
		per_user = false,
	},
	{
		type = "int-setting",
		name = "particleduration",
		setting_type = "startup",
		default_value = 20,
		maximum_value = 9999999,
		minimum_value = 0,
		order = "j",
		per_user = false,
	},
	})
	